version: '2.3'

services:
  main:
    container_name: SignBoardMatching
    build:
      context: ./
      dockerfile: 'docker/Dockerfile'
    runtime: nvidia
    restart: always
    ipc: "host"
    env_file:
      - "docker/main.env"
    expose:
      - "8888"
      - "8000"
      - "22"
    ports:
      - "18000:8000"
      - "18888:8888"
      - "10022:22"
    stdin_open: true
    tty: true
