version: '2.3'
  
services:
  main:
    container_name: "SignMatching_SIFT_VIT"
    build:
      context: "./docker"
      dockerfile: Dockerfile
    runtime: nvidia
    restart: always
    env_file:
      - "./docker/main.env"
    volumes:
      - "./:/workspace/"
    expose:
      - "8000"
    ports:
      - "45000:8888"
      - "45001:8097"
      - "45002:22"
    ipc: host
    stdin_open: true
    tty: true
